name: 'Test Giphy'
on:
    pull_request: 
        types:
            - opened
jobs:
    testing-action:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Post PR comment
              uses: parth93QA/docker-action-pr-giphy-comment@main
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                giphy-api-key: ${{ secrets.GIPHY_API_kEY }}

            - name: Post PR comment
              uses: parth93QA/js-giphy-pr@test
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  giphy-api-key: ${{ secrets.GIPHY_API_kEY }}